[opener]
edit = [
  { run = '${EDITOR:=nvim} "$@"', desc = "$EDIT", block = true, for = "unix" },
  { run = '${EDITOR:=code} "$@"', desc = "$CODE", block = true, for = "unix" },
]

[manager]
sort_by = "alphabetical"
sort_sensitive = false
sort_dir_first = true
show_symlink = true
show_hidden = true
linemode = "mtime"
